FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["src/EventHub.Web/EventHub.Web.csproj", "src/EventHub.Web/"]
RUN dotnet restore "src/EventHub.Web/EventHub.Web.csproj"
COPY . .
WORKDIR "/src/src/EventHub.Web"

RUN dotnet dev-certs https -v -ep localhost.pfx -p e8202f07-66e5-4619-be07-72ba76fde97f
RUN dotnet dev-certs https -ep ${HOME}/.aspnet/https/aspnetapp.pfx -p e8202f07-66e5-4619-be07-72ba76fde97f
RUN dotnet dev-certs https --trust 
RUN dotnet build "EventHub.Web.csproj" -c Release -o /app

FROM build AS publish
RUN dotnet publish "EventHub.Web.csproj" -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "EventHub.Web.dll"]