ARG BASE_IMAGE=base

FROM ${BASE_IMAGE} AS base

WORKDIR /app/eventhub/src/EventHub.DbMigrator
RUN dotnet publish -c Release -o bin/Release/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS publish
WORKDIR /app
COPY --from=base /app/eventhub/src/EventHub.DbMigrator/bin/Release/publish .
ENTRYPOINT ["dotnet", "EventHub.DbMigrator.dll"]