apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-{{ .Chart.Name }}
spec:
  serviceName: {{ .Release.Name }}-{{ .Chart.Name }}
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Chart.Name }}
    spec:
      containers:
        - image: postgres:13-bullseye
          name: {{ .Release.Name }}-{{ .Chart.Name }}
{{- if eq .Release.Name "eh-az" }}
          volumeMounts:
          - mountPath: "/var/lib/postgresql/data"
            name: {{ .Release.Name }}-{{ .Chart.Name }}-database-volume
            subPath: postgresql-data
{{- end }}
          ports:
            - name: postgresql
              containerPort: 5432
          env:
          - name: POSTGRES_USER
            value: "root"
          - name: POSTGRES_PASSWORD
            value: "root"
{{- if eq .Release.Name "eh-az" }}
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-{{ .Chart.Name }}-database-volume
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "managed-csi"
      resources:
        requests:
          storage: 32Gi
{{- end }}