FROM mcr.microsoft.com/dotnet/sdk:5.0 as build-image

WORKDIR /.
COPY ./*/*.csproj ./
RUN for file in $(ls *.csproj); do mkdir -p ./${file%.*}/ && mv $file ./${file%.*}/; done
RUN dotnet restore "EventHub.Web/EventHub.Web.csproj" --verbosity detailed
COPY . .
RUN dotnet publish ./EventHub.Web/EventHub.Web.csproj -o /publish/
FROM mcr.microsoft.com/dotnet/aspnet:5.0
WORKDIR /publish
COPY --from=build-image /publish .
ENV ASPNETCORE_URLS="http://0.0.0.0:80"
ENTRYPOINT ["dotnet", "EventHub.Web.dll"]



