ARG BASE_IMAGE=base

FROM ${BASE_IMAGE} AS base

WORKDIR /app/eventhub/src/EventHub.IdentityServer
RUN dotnet publish -c Release -o bin/Release/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0 AS publish
WORKDIR /app
EXPOSE 80
ENV ASPNETCORE_URLS=http://+:80
COPY --from=base /app/eventhub/src/EventHub.IdentityServer/bin/Release/publish .
ENTRYPOINT ["dotnet", "EventHub.IdentityServer.dll"]